config/routes.rb
Rails.application.routes.draw do
  resources :sharks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "sharks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/shark.rb
class Shark < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    validates :facts, presence: true, length: {minimum:5, maximum:100}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    http_basic_authenticate_with name: 'Edward', password: 'shark', except: [:index, :show]
end

app/controllers/sharks_controller.rb
class SharksController < ApplicationController
  before_action :set_shark, only: %i[ show edit update destroy ]

  # GET /sharks or /sharks.json
  def index
    @sharks = Shark.all
  end

  # GET /sharks/1 or /sharks/1.json
  def show
  end

  # GET /sharks/new
  def new
    @shark = Shark.new
  end

  # GET /sharks/1/edit
  def edit
  end

  # POST /sharks or /sharks.json
  def create
    @shark = Shark.new(shark_params)

    respond_to do |format|
      if @shark.save
        format.html { redirect_to shark_url(@shark), notice: "Shark was successfully created." }
        format.json { render :show, status: :created, location: @shark }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sharks/1 or /sharks/1.json
  def update
    respond_to do |format|
      if @shark.update(shark_params)
        format.html { redirect_to shark_url(@shark), notice: "Shark was successfully updated." }
        format.json { render :show, status: :ok, location: @shark }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sharks/1 or /sharks/1.json
  def destroy
    @shark.destroy

    respond_to do |format|
      format.html { redirect_to sharks_url, notice: "Shark was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shark
      @shark = Shark.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shark_params
      params.require(:shark).permit(:name, :facts)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sharks_helper.rb
module SharksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SharkApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sharks/_form.html.erb
<%= form_with(model: shark, local: true) do |form| %>
  <% if shark.errors.any? %>
    <div id="error_explanation" class="error_explanation_prompt" style="color: red">
      <h2 class="error_counter"><%= pluralize(shark.errors.count, "error") %> prohibited this shark from being saved:</h2>

      <ul>
        <% shark.errors.each do |error| %>
          <li class="error_list"><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :facts, style: "display: block" %>
    <%= form.text_area :facts, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.submit(class: 'btn btn-success') %>
  </div>
<% end %>

app/views/sharks/_shark.html.erb
<div id="<%= dom_id shark %>">
  <p>
    <strong>Name:</strong>
    <%= shark.name %>
  </p>

  <p>
    <strong>Facts:</strong>
    <%= shark.facts %>
  </p>

</div>

app/views/sharks/edit.html.erb
<h1 class="shark_edit_title">Editing shark</h1>

<%= render "form", shark: @shark %>

<br>

<div>
  <%= link_to "Show this shark", @shark, class: 'btn btn-default' %> |
  <%= link_to "Back to sharks", sharks_path, class: 'btn btn-default' %>
</div>

app/views/sharks/index.html.erb
<p style="color: green" id="notice" class="show_alert"><%= notice %></p>
<div class="facts_container">
<h1 class="shark_home_title">Sharks</h1>

<table class="container">
<thead>
  <tr>
    <th> Name </th>
    <th> Facts </th>
    <th colspan="3"></th>
  </tr>
<thead>

<tbody>
  <% @sharks.each do |shark|%>
    <tr class="show-table">
      <td> <%= shark.name %> </td>
      <td> <%= shark.facts %> </td>
      <td> <%= link_to 'Show', shark, class: 'btn btn-default' %> </td>
      <td> <%= link_to 'Edit', edit_shark_path(shark), class: 'btn btn-default' %> </td>
      <td> <%= link_to 'Destroy', shark, method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger' %> </td>
    </tr>
  <% end %>
</tbody>
</table>

<div class="new_shark_btn container">
<%= link_to "New shark", new_shark_path, class: 'btn btn-success' %>
</div>
</div>

app/views/sharks/new.html.erb
<h1 class="form_shark_title">New shark</h1>

<%= render "form", shark: @shark %>

<br>

<div class="back-to_prev_shark_state ">
  <%= link_to "Back to sharks", sharks_path, class: 'btn btn-default' %>
</div>

app/views/sharks/show.html.erb
<p style="color: green" class="show_alert"><%= notice %></p>
<div class="destroy_shark_details">
  <%= render @shark %>
</div>

<div>
  <div class="prev_shark">
  <%= link_to "Edit this shark", edit_shark_path(@shark), class: 'btn btn-default' %> |
  <%= link_to "Back to sharks", sharks_path, class: 'btn btn-default' %>
  </div>

  <div class="destroy_shark">
  <%= button_to "Destroy this shark", @shark, method: :delete, class: 'btn btn-danger' %>
  </div>
</div>